### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by daurnimator** [brimworks/lua-zlib#23]
I compiled/installed via luarocks:

```
$ sudo luarocks install lua-zlib
Installing https://rocks.moonscript.org/lua-zlib-0.3-1.rockspec...
Using https://rocks.moonscript.org/lua-zlib-0.3-1.rockspec... switching to 'build' mode
Cloning into 'lua-zlib'...
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 17 (delta 0), reused 11 (delta 0)
Receiving objects: 100% (17/17), 11.82 KiB | 0 bytes/s, done.
Checking connectivity... done.
Note: checking out 'c0014bcbc4c3fd65ba3519b10965f0c184c1a059'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

gcc -O2 -fPIC -I/usr/include -c lua_zlib.c -o lua_zlib.o
gcc -shared -o zlib.so -L/usr/lib lua_zlib.o
Updating manifest for /usr/lib/luarocks/rocks-5.2
lua-zlib 0.3-1 is now built and installed in /usr (license: MIT)
```

However, when trying to run (e.g, via `lua -lzlib`), I get:

    /usr/lib/lua/5.2/zlib.so: undefined symbol: inflate

The fix seems to be renaming the shared object, e.g. to `lua-zlib.so`.
I assume this is due to the dynamic linker getting confused?

**Comment by daurnimator** [comment]
> The inflate symbol should come from libz.so. Perhaps the problem is when linking zlib.so, you need to pass the -lz flag to the linker to tell it that the libz.so is NEEDED.

That seems to work.

>  Perhaps this means the rockspec needs to be updated to tell the linker to pass the -lz flag, but I'm no expert in rockspec's, so I'm not sure how to do that.

Add 'z' to the libraries array, so instead of 
```lua
    zlib = "lua_zlib.c"`
```

Have: 

```lua
    zlib = {
        sources = { "lua_zlib.c" };
        libraries = { "z" },
    };
```

**Comment by brimworks** [comment]
Okay, I think this is fixed (and I finally got around to using luarocks a bit). 

`luarocks install lua-zlib` will install the latest which has the fix (0.4-1 version).

On my Mac, I can now properly see the NEEDED field is set for libz:

> otool -L /usr/local/lib/lua/5.2/zlib.so

/usr/local/lib/lua/5.2/zlib.so:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 283.0.0)

Thanks,
-Brian

**Comment by daurnimator** [comment]
> luarocks install lua-zlib will install the latest which has the fix (0.4-1 version).

The new rockspec has not been uploaded to moonrocks yet? https://rocks.moonscript.org/search?q=lua-zlib

**Comment by brimworks** [comment]
It is there: https://rocks.moonscript.org/search?q=lua-zlib&non_root=on

I would like to take ownership of this rock, just not sure how I should do that.

Thanks,
-Brian

**Comment by daurnimator** [comment]
> I would like to take ownership of this rock, just not sure how I should do that.

You need to poke @leafo and/or @hishamhm who will fix it up for you.

**Comment by guilhem** [comment]
I can manage it next week if you are asking gently ;)

**Comment by leafo** [comment]
I can transfer it right now now, sound good @brimworks

**Comment by brimworks** [comment]
Thanks! No big rush :).

**Comment by leafo** [comment]
Alright, good to go: http://rocks.moonscript.org/modules/brimworks/lua-zlib 

I also copied the older versions into your copy of the module

**Comment by guilhem** [comment]
I deleted mine for less confusion
