### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by daurnimator** [brimworks/lua-zlib#24]
this library has the same 'require' string as [lzlib](https://github.com/LuaDist/lzlib)

Installing this module can cause some weird failures around the place, [including luarocks, which uses lzlib when installed](https://github.com/keplerproject/luarocks/blob/fa6863a19d3dd40c43975ffb4b3384d9cad40228/src/luarocks/tools/zip.lua#L7)

Could you rename the shared object lua-zlib gets installed as?

**Comment by brimworks** [comment]
I'm afraid this is a long standing issue :(. I'm not sure how best to solve this issue since it would cause backwards compatibility problems. When I wrote lua-zlib, I didn't know about lzlib. Suggestions and pull requests are welcomed (as long as it doesn't alienate existing users).

**Comment by daurnimator** [comment]
I filed the bug here rather than on lzlib, as looking through a few projects, your project was (sadly) the less popular one.

Maybe if you renamed the library to "lua-zlib" but provided a 'zlib.lua' shim for compatability purposes that just contained:

    return require "lua-zlib"

**Comment by brimworks** [comment]
Good idea, although I'm not fond of renaming mine to "lua-zlib". How about "compress.zlib" instead? I think the lzlib project is abandoned :(. Do you want to send a pull request for this? If not, I'll see about getting some time to make this adjustment. Also if you have a better naming idea, let me know.

Thanks,
-Brian

**Comment by daurnimator** [comment]
> How about "compress.zlib" instead?

That doesn't really make sense to me; that sounds like part of a suite of tools for compression; or to something called 'libcompress' or some such.


> if you have a better naming idea, let me know.

I'm trying to think of something.... 
  - "brimworks.zlib"
  - "z"; precedent in `-lz` linker flag

**Comment by daurnimator** [comment]
any ideas here?

**Comment by brimworks** [comment]
Perhaps I should create a superset interface so that any API calls that "look" like lzlib act the same as lzlib. I could simply copy over the lzlib code.

Thoughts?

Thanks,
-Brian

**Comment by daurnimator** [comment]
I don't know if that's the best idea.... though perhaps it provides us a way out: lzlib isn't maintained as far as I know; so adding a backwards compatible API, then asking the lua community to essentially deprecate lzlib might work. @hishamhm what do you think? luarocks is probably the most important application to convince.

FWIW I did make an abstraction layer of lua-zlib/lzlib: https://github.com/daurnimator/lua-http/blob/master/http/zlib.lua

**Comment by hishamhm** [comment]
Nowadays we also have [a compatibility layer in LuaRocks](https://github.com/keplerproject/luarocks/blob/c2bad31e7fea154c3fdee453b2d774f48b422be8/src/luarocks/tools/zip.lua#L12-L41). I think adding a backwards compatible API in lua-zlib is the simplest approach for projects down the road. The lzlib package is [under my account in luarocks.org](https://luarocks.org/modules/hisham/lzlib), because I had to tweak Lua 5.3 compatibility into it. Once lua-zlib becomes compatible, I can edit its description to say it's deprecated and direct people to lua-zlib. There are a couple other projects using lzlib in luarocks.org, ideally one should contact them too.

**Comment by brimworks** [comment]
Thanks for the feedback! I'll work on making lua-zlib backwards compatible with lua-lzlib and make sure it works with Lua 5.3. I should be able to do this in the next month.

Thanks,
-Brian

**Comment by hishamhm** [comment]
Awesome! Make sure to ping me when you're done!

**Comment by daurnimator** [comment]
btw, you should be able to make the backwards compat layer in pure lua. That should make it easy to maintain :)

**Comment by brimworks** [comment]
Although I like the idea of a pure lua layer, implementing isn't as straight forward (and not as strictly backwards compatible). So, I simply imported the code from lzlib:

https://github.com/brimworks/lua-zlib/commit/7de195f5f2ac4f1f8522ae241c123fb7bff29595

Feedback is welcomed. I tested this by running `luarocks make` against lua 5.2 and 5.3. I also manually did some tests using the lzlib interface, but only minimally so.

Thanks,
-Brian

**Comment by brimworks** [comment]
@hishamhm and @daurnimator do you have any comments on my proposal?

https://github.com/brimworks/lua-zlib/commit/7de195f5f2ac4f1f8522ae241c123fb7bff29595

If I get a thumbs up, then I can upload a new lua rock release and close this issue.

Thanks,
-Brian

**Comment by hishamhm** [comment]
Sounds good to me! Thank you for the initiative!

**Comment by daurnimator** [comment]
Looks good to me.

**Comment by brimworks** [comment]
I've published this as v1.0.0 on luarocks:

https://luarocks.org/modules/brimworks/lua-zlib

Thanks,
-Brian

**Comment by daurnimator** [comment]
Thanks! my test matrix is complete for the first time: https://github.com/daurnimator/lua-http/commit/c9fafa13fd6b664dec297f11670f79982571fcf8

**Comment by daurnimator** [comment]
@hishamhm would you consider pushing people looking at http://luarocks.org/modules/hisham/lzlib over to lua-zlib instead?
