### ISSUE TITLE
Add 5.3 to rockspec

### ISSUE THREAD

**Issue by daurnimator** [brimworks/lua-zlib#28]
Currently the rockspec claims compatibility with only >= 5.1 < 5.3.

**Comment by brimworks** [comment]
I haven't tried compiling with 5.3, does it actually work with 5.3?

Thanks,
-Brian

**Comment by daurnimator** [comment]
Yes; I think it does. Didn't bc327e3ea486d0e9316d208a8d13fe0ed13deb68 add that?

**Comment by daurnimator** [comment]
ping?

**Comment by brimworks** [comment]
Sorry about that, I must have been on vacation and lost track of this. Here is the commit: https://github.com/brimworks/lua-zlib/commit/dc43eaa1f5d4f523cfde2dd32097796199dbdf07

Unfortunately, luarocks is temporarily broken on my system, so I'll need a bit of time to fix it and upload the new rockspec.

Thanks,
-Brian

**Comment by daurnimator** [comment]
> luarocks is temporarily broken on my system, so I'll need a bit of time to fix it and upload the new rockspec.

You can upload from the website: https://luarocks.org/upload

**Comment by brimworks** [comment]
Thanks! I've uploaded the new rockspec:

http://luarocks.org/modules/brimworks/lua-zlib/0.4-2

**Comment by daurnimator** [comment]
That doesn't work with 5.3: the patch adding 5.3 support wasn't included in the 0.4 tag.
(please take the non working rockspec down?)

**Comment by brimworks** [comment]
Hum... I'll have to test this when I get a chance. I've taken down version 0.4-2.

Sorry,
-Brian

**Comment by brimworks** [comment]
At last I got time to sort out my lua versions... started using `luaver` so I can test against all the lua versions :). It looks like the piece I missed previously was to tag the new version. I've published 0.5-0 to luarocks, and this time I tested that it works with 5.3.3 and 5.2.4.

Next up is to add a compatibility shim so lua-zlib can be used as a replacement for lzlib.
