### ISSUE TITLE
Failure on install and lua test.lua commands

### ISSUE THREAD

**Issue by josh-lane** [brimworks/lua-zlib#33]
Can someone set me straight on these?

When running lua test.lua I get this error.
**lua: test.lua:8: module 'zlib' not found:
        no field package.preload['zlib']
        no file './zlib.lua'
        no file '/usr/local/share/lua/5.2/zlib.lua'
        no file '/usr/local/share/lua/5.2/zlib/init.lua'
        no file '/usr/local/lib/lua/5.2/zlib.lua'
        no file '/usr/local/lib/lua/5.2/zlib/init.lua'
        no file './zlib.lua'
        no file '/usr/share/lua/5.2/zlib.lua'
        no file '/usr/share/lua/5.2/zlib/init.lua'
        no file './zlib.lua'
        no file './zlib.so'
        no file '/usr/local/lib/lua/5.2/zlib.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2/zlib.so'
        no file '/usr/lib/lua/5.2/zlib.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './zlib.so'
stack traceback:
        [C]: in function 'require'
        test.lua:8: in main chunk
        [C]: in ?**

When running make linux I get this error:
**make[1]: Entering directory `/home/josh/lua-zlib'
gcc -O -shared -fPIC -L/usr/lib -L/usr/lib lua_zlib.o -lz -llua -lm -o zlib.so
/usr/bin/ld: cannot find -llua
collect2: ld returned 1 exit status
make[1]: *** [zlib.so] Error 1**

I have installed lua5.1 and lua5.2 as well.  Any help you can provide?

**Comment by brimworks** [comment]
This is the key error:

/usr/bin/ld: cannot find -llua

The linker can't find liblua.so. To fix this it depends on your OS distribution.

Cheers,
-Brian

**Comment by josh-lane** [comment]
I can create a basic .lua file and it works with the lua command.  I've got lua5.1 & lua5.2 on the system but neither one seem to be picked up by this process.  This is where I'm confused.
