### ISSUE TITLE
Mac install make error

### ISSUE THREAD

**Issue by Aokicu** [brimworks/lua-zlib#34]
Hello ,I need help.When I install lua-zlib on mac, some error message as following:
[ 50%] Building C object CMakeFiles/cmod_zlib.dir/lua_zlib.c.o
[100%] Linking C shared module zlib.so
Undefined symbols for architecture x86_64:
  "_luaL_argerror", referenced from:
      _lz_checksum in lua_zlib.c.o
  "_luaL_buffinit", referenced from:
      _lz_filter_impl in lua_zlib.c.o
  "_luaL_checklstring", referenced from:
      _lz_checksum in lua_zlib.c.o
  "_luaL_checkoption", referenced from:
      _lz_filter_impl in lua_zlib.c.o
  "_luaL_newmetatable", referenced from:
      _lz_create_deflate_mt in lua_zlib.c.o
      _lz_create_inflate_mt in lua_zlib.c.o

what should I do??

**Comment by rocky-zh** [comment]
i have the same error in mac os x;

```shell
  "_lua_type", referenced from:
      _lz_filter_impl in lua_zlib.c.o
      _lz_checksum in lua_zlib.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by brimworks** [comment]
It looks like the lua headers you compiled with don't match up with the lua library you linked with.
