### ISSUE TITLE
[ lua test.lua ] failed

### ISSUE THREAD

**Issue by nizqsut** [brimworks/lua-zlib#38]
the result of "lua test.lua" like this:

cc@ubuntu:~/git/lua-zlib$ lua test.lua 
1..9
ok 1 - eof is true (true)
ok 2 - bytes in is greater than bytes out?
ok 3 - bytes out is the same size as deflated string length
ok 4 - bytes in is the same size as the input string length
ok 5 - Expected 8192 Xs got 8192
ok 6
ok 7 - 'abcdefghijklmnopqrstuv' == 'abcdefghijklmnopqrstuv'
ok 8 - large string
ok 9 - empty string
ok 10
ok 11 - InvalidInput error (InvalidInput: input string does not conform to zlib format or checksum failed at lua_zlib.c line 994)
EOF round
ok 12 - streaming works
ok 13 - IllegalState error (IllegalState: calling deflate function when stream was previously closed)
ok 14 - major version 1 == 1
ok 15 - minor version is number (2)
ok 16 - patch version is number (11)
ok 17 - Tom MacWright Test

And in the source code lua_zlib.c line 994. There is a comment:

    do {
        stream->next_out  = (unsigned char*)luaL_prepbuffer(&buff);
        stream->avail_out = LUAL_BUFFERSIZE;
        result = filter(stream, flush);
        if ( Z_BUF_ERROR != result ) {
            /* Ignore Z_BUF_ERROR since that just indicates that we
             * need a larger buffer in order to proceed.  Thanks to
             * Tobias Markmann for finding this bug!
             */
            lz_assert(L, result, stream, __FILE__, __LINE__);
        }
        luaL_addsize(&buff, LUAL_BUFFERSIZE - stream->avail_out);
    } while ( stream->avail_out == 0 );

Just ask this bug has been fixed or not?

**Comment by nizqsut** [comment]
And the libz version is 1.2.11

**Comment by brimworks** [comment]
Hello,

The output of `lua test.lua` shows all success. If you look here:

https://github.com/brimworks/lua-zlib/blob/master/test.lua#L124

You will see that I'm simply testing that invalid input produces an invalid input error.

...so I don't know of any bug here.

The comment you mention is simply that Z_BUF_ERROR needs to be ignored (and therefore the lz_assert() is NOT called when we get a Z_BUF_ERROR).
