### ISSUE TITLE
Erroneous EOF signal / stream closure when inflating some gzipped files

### ISSUE THREAD

**Issue by boydgreenfield** [brimworks/lua-zlib#41]
I'm using `lua-zlib` for streaming decompression of gzipped data coming into OpenResty as `multipart/form-data`. While everything is working _great_ for the vast majority of files I've tested, I have run into an odd edge case (see links at bottom).

Specifically, for some files, it looks like the `stream(data)` operation for an inflate stream is erroneously returning `eof = true` early, and then I get the following error message when trying to inflate the next chunk of the file:

```
2018/03/06 00:46:22 [error] 7#7: *2 lua entry thread aborted: runtime error: IllegalState: calling inflate function when stream was previously closed
stack traceback:
coroutine 0:
	[C]: in function 'stream'
	/app/./lua/gunzip_upload.lua:28: in function </app/./lua/gunzip_upload.lua:1>, client: 172.17.0.1, server: , request: "POST /gunzip_upload HTTP/1.1", host: "localhost:8080"
```

In looking at this further, it appears `stream()` is returning `eof = true`, despite being in the middle of the file. 

**Setup details**
Specifically, I'm using [`lua-resty-upload`](https://github.com/openresty/lua-resty-upload) and then just uncompressing the stream with some code that looks like this (modified from their example for here, this is just a `content_by_lua` block in OpenResty).

Here's a minimal example of my lua script (`gunzip_upload.lua`):

```lua
local zlib = require "zlib"
local upload = require "resty.upload"

local stream = zlib.inflate(31)
local chunk_size = 4096
local form = upload:new(chunk_size)
local file
while true do
    local typ, res, err = form:read()

    if not typ then
         ngx.say("failed to read: ", err)
         return
    end

    if typ == "header" then
        -- Contrived example to just unzip a file and write it out as "unzipped.txt"
        -- This will *only* work with gzipped uploads
        local file_name = "unzipped.txt"
        if file_name then
            file = io.open(file_name, "w+")
            if not file then
                ngx.say("failed to open file ", file_name)
                return
            end
        end

     elseif typ == "body" then
        if file then
            body, gzip_eof, bytes_in, bytes_out = stream(res)
            file:write(body)
        end

    elseif typ == "part_end" then
        file:close()
        file = nil

    elseif typ == "eof" then
        break

    else
        -- do nothing
    end
end

```

And an example `nginx.conf`:

```nginx
worker_processes 1;
error_log logs/error.log;

events {
  worker_connections 256;  
}

http {
  server {
    listen 8080;
    client_max_body_size 5G;
    client_body_buffer_size 4M;
    keepalive_timeout 300s;
    proxy_read_timeout 600s;
    lua_code_cache off;  # For dev, turn `off` for hot reloading!

    location = /gunzip_upload {
      if ($request_method != POST ) {
        return 405;
      }

      content_by_lua_file ./lua/gunzip_upload.lua;
    }
  }
}
```

(_Note you can actually just inline `gunzip_upload.lua` with a `content_by_lua` block_)

**Unfortunately** the file I have where I can reliably reproduce this is 1.9GB. _But_ this still triggers the failure for the first 40MB chunk, though note that's not actually a valid gzip file as it isn't complete.
- Full file (~2GB): [link](https://drive.google.com/a/onecodex.com/file/d/1NnEBN9CFpIP54TEy29VkFM_nAGc2g7Tl/view?usp=drive_web)
- 40MB file: [link](https://drive.google.com/a/onecodex.com/file/d/1godKWo7p3Eu9zFWn2qMtAn0jgddN-Ku9/view?usp=drive_web)

Many thanks in advance for the help, the library is otherwise working great for our needs! 👏

**Comment by brimworks** [comment]
Can you reproduce this outside of nginx?

**Comment by boydgreenfield** [comment]
@brimworks Sorry, I missed your note. Let me try to reproduce with a standalone script.

**Comment by boydgreenfield** [comment]
@brimworks Here's a minimal script that reproduces with the above files:

```lua
local zlib = require "zlib"

local file = io.open(arg[1], "r")
local chunk_size = 4096
local bytes_read = 0

local stream = zlib.inflate()
print(string.format("Reading file %s...", arg[1]))

while true do
	local chunk = file:read(chunk_size)
	if not chunk then
		print(string.format("Done! Read %d bytes total.", bytes_read))
		break
	end
	bytes_read = bytes_read + chunk:len()
	local uncompressed_chunk = stream(chunk)
end
```

When I invoke on _most_ files, I get a result like this:

```
08:38:05 {master} ~/lua-gzip-issue $ lua gunzip.lua first100k.fastq.gz 
Reading file first100k.fastq.gz...
Done! Read 5555810 bytes total.
```

On the above (smaller) file:

```
08:39:01 {master} ~/lua-gzip-issue $ lua gunzip.lua compressed.40mb.fastq.gz 
Reading file compressed.40mb.fastq.gz...
lua: IllegalState: calling inflate function when stream was previously closed
stack traceback:
	[C]: in local 'stream'
	gunzip.lua:17: in main chunk
	[C]: in ?
```

**Comment by brimworks** [comment]
I'm not sure why I didn't realize this before, but your not properly checking the end of stream. Specifically the call to `stream(chunk)` returns 4 values:

- The uncompressed chunk
- The end of file indicator
- The number of bytes "in"
- The number of bytes "out"

Perhaps the library should be a bit more forgiving when one assumes that a nil uncompressed chunk is sufficient as an end of file indicator?

...so to fix your code and get you going again, I'd suggest making this change:

```lua
local zlib = require "zlib"

local file = io.open(arg[1], "r")
local chunk_size = 4096
local bytes_read = 0

local stream = zlib.inflate()
print(string.format("Reading file %s...", arg[1]))

local eof = false
while not eof do
	local chunk = file:read(chunk_size)
	if not chunk then
		print(string.format("Done! Read %d bytes total.", bytes_read))
		break
	end
	bytes_read = bytes_read + chunk:len()
	local uncompressed_chunk
	uncompressed_chunk, eof = stream(chunk)
end
```

**Comment by brimworks** [comment]
...also note that `stream(chunk)` only throws an error like this if called with a string input, which is why this occurs only when a gzip stream has "extra stuff" at the end.

Do you think `stream(chunk)` should ignore this situation and simply always return nil?

**Comment by brimworks** [comment]
I've tested that this fixes your issue:

https://github.com/brimworks/lua-zlib/commit/9cd7379d0d2526f9ab01ee58d5c7420de2758831

...although I'd like to see if this is the desired behavior before I push it more globally. 

@hishamhm what do you think?

**Comment by boydgreenfield** [comment]
@brimworks I'll try to test this out this evening. Note that I was just breaking when there was no more _input_ to read. The smaller gzipped file I attached above _is_ invalid because it has extra bytes at the end, but this bug I'm running into is occurring _before_ that point. The larger file is a complete (and as far as I can tell well-formed) gzip file that doesn't have any extra bytes at the end.

**Comment by hishamhm** [comment]
@brimworks the new behavior you suggest sounds harmless enough, as you _are_ still getting the eof return in the second argument (and according to @boydgreenfield other libraries e.g. Python seem to ignore extra trailing data as well).

> The larger file is a complete (and as far as I can tell well-formed) gzip file that doesn't have any extra bytes at the end.

@boydgreenfield so something else inside the file makes it close the stream? 2GB sounds suspicious: is the library overflowing an `int` (signed 32-bit = 2GB) somewhere?

**Comment by boydgreenfield** [comment]
@brimworks While this patch fixes the issue I'm having _if you ignore the `eof` return value_, it unfortunately looks like:
- It improperly returns `eof` for these files early, so you could end up not processing the whole file
- It returns `eof` true for the truncated file, which `gunzip` and other tools fail on because it _isn't_ a complete file

Here's an updated script capturing the `eof`, `bytes_in`, and `bytes_out` variables:

```lua
local zlib = require "zlib"

local file = io.open(arg[1], "r")
local chunk_size = 8193
local bytes_read = 0

local stream = zlib.inflate()
print(string.format("Reading file %s...", arg[1]))

local eof = false
local bytes_in = 0
local bytes_out = 0
while true do
	local chunk = file:read(chunk_size)
	if not chunk or eof then
		print(string.format("Done! Read %d bytes total.", bytes_read))
		break
	end
	bytes_read = bytes_read + chunk:len()
	local uncompressed_chunk
	uncompressed_chunk, eof, bytes_in, bytes_out = stream(chunk)
end

print(string.format("Reached EOF? %s", eof))
print(string.format("Total uncompressed bytes: %d", bytes_out))
```

For a correct file, this reads the entire file, and outputs the number of bytes in the uncompressed file:

```
02:46:44 {issue-41} ~/OC/lua-zlib$ lua gunzip.lua ../fastx-proxy/first100k.fastq.gz 
Reading file ../fastx-proxy/first100k.fastq.gz...
Done! Read 5555810 bytes total.
Reached EOF? true
Total uncompressed bytes: 19112446
```

However, for both my files, this fails because `eof` is set early (and oddly, `bytes_in` is also nil here too):

```
02:46:50 {issue-41} ~/OC/lua-zlib$ lua gunzip.lua ~/Downloads/compressed.fastq.gz 
Reading file /Users/boyd/Downloads/compressed.fastq.gz...
Done! Read 17533020 bytes total.
Reached EOF? true
Total uncompressed bytes: 78643200
```
(The above file is nearly 2GB)

**Comment by brimworks** [comment]
BTW, I've downloaded the 2GB file and reproduced the problem. However, I don't have any idea on root cause at this moment. Thanks for reporting the problem.

**Comment by boydgreenfield** [comment]
@brimworks Thanks for the update. Our full release of the tool using this library is somewhat blocked by this, but I think I'm going to deploy the service we've built for internal end-users for now and try to log when/if we run into this issue again. Hopefully that will produce some more reproducible test cases and lend insight into what may be going on.

Thanks again for your help here!

**Comment by boydgreenfield** [comment]
@brimworks I've seen a couple more examples of this in the wild, but haven't gotten any closer to understanding what's causing this. If you have any initial thoughts, I'd be happy to try and dig in a bit with the above test case, but I'm not particularly familiar with `zlib` (or even Lua for that matter), so would appreciate any intuition/guidance on where you'd recommend starting... Thanks again.

**Comment by brimworks** [comment]
@boydgreenfield if you can provide some more cases that reproduce this problem, it would be helpful.

Thanks,
-Brian

**Comment by boydgreenfield** [comment]
@brimworks I'll try to find more examples to reproduce beyond the original above (I realize the 2GB file is a pain...). Unfortunately, the few other cases I've seen involve third parties' data and can't be shared directly.

**Comment by boydgreenfield** [comment]
In looking at the zlib documentation, I _think_ this may be an issue with the chunk size and not calling `gzclearerr`. I'll investigate this a bit further.

**Comment by boydgreenfield** [comment]
OK, I've got this fixed on our end. I _believe_ the issue here is that GZIP allows concatenation of valid files, and it appears some gzip files have these internal boundaries and headers, which causes naïve use of `inflate` for all of the data to fail. 

For reference, our ultimate workaround was something like this:

```lua
body, gzip_eof, bytes_in, bytes_out = inflate_stream(data)
local total_bytes_in = bytes_in + bytes_in_remainder
if total_bytes_in ~= total_data_read then  -- note this is how much we've seen in the stream
    bytes_in_remainder = bytes_in_remainder + bytes_in
    inflate_stream = zlib.inflate()
    local old_body = body
    local new_start_pos = 1 + total_bytes_in - (upload_size_bytes - string.len(res))
    body, gzip_eof, bytes_in, bytes_out = inflate_stream(string.sub(data, new_start_pos, string.len(data)))
    body = old_body .. body 
    total_bytes_in = total_bytes_in + bytes_in
end
```

It did _not_ require mucking with `zlib` and, upon further investigation, `inflateReset` is not the right function for this anyway.

This can probably be closed, but I'll leave that up to you @brimworks. Thanks again for all the help here!

**Comment by brimworks** [comment]
Oh, this makes sense! Do you think simply documenting this is sufficient? Or should we assume the EOF indicator should only be respected when a nil is passed to inflate?

@hishamhm do you have thoughts on this?

**Comment by hishamhm** [comment]
> I believe the issue here is that GZIP allows concatenation of valid files

Oh wow, I had no idea!

```bash
$ ls -l file.jpg
-rw-r--r-- 1 hisham users 289517 May 11 16:08 file.jpg
$ dd if=file.jpg bs=100000 count=1 | gzip > part1.gz
$ dd if=file.jpg bs=100000 count=1 skip=1 | gzip > part2.gz
$ dd if=file.jpg bs=100000 count=1 skip=2 | gzip > part3.gz
$ cat part1.gz part2.gz part3.gz > allparts.gz
$ gunzip allparts.gz
$ ls -l allparts
-rw-r--r-- 1 hisham users 289517 Jun  4 21:03 allparts
$ diff file.jpg allparts
$ echo $?
0
$ ls -l allparts
```

@brimworks if since the library supports skipping the first gzip header, then maybe it should skip any following ones as well?

**Comment by brimworks** [comment]
Ya, I think if my library simply ignores the EOF (by re-initializing the stream) from the gzip library unless a nil is passed in (which would indicate that the stream is complete) then that should be sufficient to get this to work, right?

**Comment by hishamhm** [comment]
yes, I think this makes sense (if I'm still following the logic correctly!). I guess the ideal would be to make the change and let @boydgreenfield give it a try!

**Comment by boydgreenfield** [comment]
@brimworks Yes, that's just what we're doing in Lua now. I wasn't really aware that this kind of concatenation was possible / I still find it kind of bizarre that we're seeing it in some files. Happy to test a fix if you do patch the library.

**Comment by cryi** [comment]
Hi,

I do not believe this is something what we should fix on library level. I swept quickly through the code and we would have to change how is input stream held in the memory to make sure we can iterate over multiple streams. While we can do this easily on lua side. 

So for me documentation adjustment is sufficient. 
Here is simple yet more complete example how I handle multi stream .gz files:
```lua
local lz = require"lz"

local f = io.open"allparts.gz"
local dest = io.tmpfile()

local inflate = lz.inflate()
local shift = 0
while true do
   x = f:read(4096)             -- we read in 4K chunks
   if not x then break end
   local inflated, eof, bytes_in, bytes_out = inflate(x)
   if eof then -- we got end of gzip stream we return to bytes_in pos in case there are multiple stream embedded
      f:seek("set", shift + bytes_in)
      shift = shift + bytes_in  -- we need to shift through in case of multiple streams
      inflate = lz.inflate()    -- we need new inflate for each stream
      dest:write(inflated)      -- do your thing with one of inflated streams
   end
end
dest:seek("set")
dest:read("a")                  -- read all inflated streams merged
```

@brimworks would you like me to add this into docs or make examples directory and include it there?

**Comment by brimworks** [comment]
@cryi thanks for figuring this out! I'd love it if you could update the documentation to have this example in it.

Thanks!
-Brian
