### ISSUE TITLE
Inability to create stable archives

### ISSUE THREAD

**Issue by MilhouseVH** [brimworks/lua-zlib#44]
I realise https://github.com/brimworks/lua-zlib/commit/8d076690cd84702d051a548740dfa0f2102dc28e has been in this repo for quite a while, but it has an unfortunate side-effect when creating archives which is affecting downstream projects that are using lua-zlib (see https://github.com/mamedev/mame/issues/3774 and https://github.com/libretro/mame/issues/69).

Would it be possible to partially revert this change, removing ` $Format:%d$` so that `git archive` produces a stable result? This is important when downloading git archives and using a checksum to verify the download. As it stands now, the contents of the archive changes when additional commits are added to the repo, even though the rev used to retrieve the archive hasn't changed.

**Comment by brimworks** [comment]
Sorry, I'm not understanding. Shouldn't the checksum change when additional commits are added to a repo regardless of the Format expansion?

**Comment by MilhouseVH** [comment]
> Shouldn't the checksum change when additional commits are added to a repo regardless of the Format expansion?

No, not normally - archives that don't include a Format expansion (which is the majority) are "stable" and you can download the archive (for example, from github) and rely[1] on the calculated checksum to verify the downloaded file even once additional commits are added to the repository (after the initial download) - additional commits to the repository do not invalidate the checksum of a previously downloaded archive because the contents of the newly downloaded archive does not change.

When using the Format specifier, the contents of the archive will change once a new commit is added which makes using checksums to verify the download almost impossible.

Effectively, by adding the Format expansion, the archives for this repo become inherently "unstable" and when any repo includes the source code of this repo (such as `mame`) they too will generate "unstable" archives - a new `mame` commit changes the contents of older, previously downloaded (and checksummed) `mame` archives - and it's only `lua_zip.c` that is changing, because of the Format expansion.

For example: If you create an archive of this repo using the current tip of tree rev 08d62517009651d0e32aa3edbf6dad58237bb11d you would see the contents of `lua_zlib.c` is:
```
    SETLITERAL("_VERSION", "lua-zlib $Id: da57e91a3a58c7f514e2058feccea7a7b42db5e2 $  (HEAD -> master, origin/master, origin/HEAD)");
```
Now add a new commit - it doesn't matter what it is - and re-generate the archive for the same rev, 08d62517009651d0e32aa3edbf6dad58237bb11d, you'll see that the contents of `lua_zlib.c` will have changed relative to the previously generated archive:
```
    SETLITERAL("_VERSION", "lua-zlib $Id: da57e91a3a58c7f514e2058feccea7a7b42db5e2 $  (tag: v1.2)");
```

This change invalidates any checksum originally calculated when the archive is first downloaded (before the addition of the new commit).

With repositories that don't include Format expansion, the archives are "stable" - the contents of the archive before the new commit and after the new commit will be identical, ensuring the checksum can be used to verify the download.

So I'd like to request that you consider removing the format expansion, unless it's absolutely vital, as it prevents this repo (and any repo using your source code, ie. `mame`, possibly others) from creating a "stable" archive, which is a problem for projects that attempt to verify archive downloads as part of their build system.

Many thanks.

1. I'm aware that git doesn't guarantee archive stability (when substitutions are not used) but the truth is they usually are, except in rare cases where the archive format changes. But a repo intentionally creating unstable archives *is* pretty rare.

**Comment by MilhouseVH** [comment]
Note that this would be the proposed change:

https://github.com/brimworks/lua-zlib/compare/master...MilhouseVH:drop_format
