### ISSUE TITLE
how can I improve percent of Building C object CMakeFiles/cmod_zlib.dir/lua_zlib.c.o

### ISSUE THREAD

**Issue by sunjiansen** [brimworks/lua-zlib#46]
![1](https://user-images.githubusercontent.com/41364558/52553573-e78a2e00-2e1e-11e9-9de8-b9b31d5a3311.jpg)

**Comment by brimworks** [comment]
The percent is generated by CMake.

**Comment by sunjiansen** [comment]
I don't understand too much，I know it is generated by CMake. ,but if I don‘t Building C object CMakeFiles/cmod_zlib.dir/lua_zlib.c.o for 100%, will it cause some other mistakes?

**Comment by brimworks** [comment]
The percentages give you a rough idea of how long it will take to build EVERYTHING. It does NOT indicate that the `CMakeFiles/cmod_zlib.dir/lua_zlib.c` was 50% built. So the output in your screenshot is normal and indicates that the zlib.so was successfully built.

**Comment by sunjiansen** [comment]
thanks a lot
